### ISSUE TITLE
Unable to go to next statement after subscribing ticker event.

### ISSUE THREAD

**Issue by jigartailor1984** [Idirect-Tech/Breeze-CSharp-SDK#8]
Using VIsual Studio 2022
.net 7

using nuget "com.breeze.breezeconnect" version 1.0.7

Following is the code I am using

```C#
// Initialize SDK 
BreezeConnect breeze = new BreezeConnect(Globals.AppKey);
// Generate Session
breeze.generateSession(Globals.SecretKey, Globals.AppSession);
var responseObject = await breeze.wsConnectAsync();
Console.WriteLine(JsonSerializer.Serialize(responseObject));

// Callback to receive ticks.
breeze.ticker((data) =>
{
    Console.WriteLine("Ticker Data:" + JsonSerializer.Serialize(data));
});

// Subscribe stocks feeds by stock-token
Console.WriteLine(JsonSerializer.Serialize(await breeze.subscribeFeedsAsync("4.1!49937")));

// Unsubscribe stocks feeds by stock-token
Console.WriteLine(JsonSerializer.Serialize(await breeze.unsubscribeFeedsAsync("4.1!49937")));

```
after call to breeze.ticker subscribe  and unsubscribe call is not executed and even in live market not able to ticker callback

<img width="867" alt="image" src="https://github.com/Idirect-Tech/Breeze-CSharp-SDK/assets/4815593/669cc3e3-31e6-4b02-8687-49e8eb1b4922">

**Comment by sureshvmax** [comment]
what is your .net version?

**Comment by jigartailor1984** [comment]
I am using **.Net 7**.
Can you please let me know if this version is supported or I need to use different version.

**Comment by jigartailor1984** [comment]
I have tried same code with .net framework 4.7.2 where I got follow error while executing statement breeze.wsConnectAsync()

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at Breeze.BreezeConnect.<wsConnectAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Demo.Program.<Main>d__0.MoveNext() in C:\MyWork\RND\BreezeAPI\Demo\Demo\Program.cs:line 19
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Demo.Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    Breeze.SocketEventBreeze.initiateSocketIOOptions(bool)
    Breeze.SocketEventBreeze.ConnectForOrder()
    Breeze.BreezeConnect.wsConnectAsyncOrder()

Inner Exception 1:
Exception: Cannot initiate connection to server. UserId or SessionToken is empty.
```
